const sb = window.supabase?.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
let PRODUCTS=[], user=null;
const cats=[['🛍️','All'],['👕','Fashion'],['📱','Electronics'],['🏠','Home & Kitchen'],['💄','Beauty'],['📦','Mobiles']];
let state={page:'home',query:'',cat:'All',cart:JSON.parse(localStorage.getItem('sk_cart')||'[]'),orders:[],wishlist:new Set(),addresses:[]};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const save=()=>localStorage.setItem('sk_cart',JSON.stringify(state.cart));
function emojiFor(c){return ({Fashion:'👕',Electronics:'📱','Home & Kitchen':'🏠',Beauty:'💄',Mobiles:'📱'})[c]||'🛍️'}
async function init(){
 if(!sb){render();toast('Supabase configuration missing');return}
 const {data:{user:u}}=await sb.auth.getUser(); user=u||null;
 await loadProducts(); await loadOrders(); await loadWishlist(); await loadAddresses(); render();
 sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;await loadOrders();await loadWishlist();await loadAddresses();render()});
}
async function loadProducts(){
 const {data,error}=await sb.from('products').select('*, categories(name)').eq('is_active',true).order('created_at',{ascending:false});
 if(error){console.error(error);toast('Products load failed');PRODUCTS=[];return}
 PRODUCTS=(data||[]).map(p=>({...p,category:p.categories?.name||'Other',emoji:emojiFor(p.categories?.name)}));
}
async function loadOrders(){if(!user){state.orders=[];return}const {data,error}=await sb.from('orders').select('*, order_items(*)').eq('user_id',user.id).order('created_at',{ascending:false});if(error)console.error(error);state.orders=data||[]}
async function loadWishlist(){state.wishlist=new Set();if(!user)return;const {data}=await sb.from('wishlists').select('product_id').eq('user_id',user.id);(data||[]).forEach(x=>state.wishlist.add(x.product_id))}
async function loadAddresses(){state.addresses=[];if(!user)return;const {data}=await sb.from('addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false});state.addresses=data||[]}
function add(id){const p=PRODUCTS.find(x=>x.id===id),x=state.cart.find(i=>i.id===id);if(!p)return;if(x&&x.qty>=p.stock)return toast('Stock limit reached');x?x.qty++:state.cart.push({id,qty:1});save();toast('Added to cart 🛒');render()}
function dec(id){const x=state.cart.find(i=>i.id===id);if(!x)return;x.qty--;if(x.qty<=0)state.cart=state.cart.filter(i=>i.id!==id);save();render()}
async function toggleWish(id){if(!user)return authBox();if(state.wishlist.has(id)){await sb.from('wishlists').delete().eq('user_id',user.id).eq('product_id',id);state.wishlist.delete(id)}else{const {error}=await sb.from('wishlists').insert({user_id:user.id,product_id:id});if(error)return toast(error.message);state.wishlist.add(id)}render()}
function productCard(p){return `<div class="card"><div class="pic">${p.image_url?`<img src="${p.image_url}" alt="${p.name}">`:p.emoji}</div><div class="body"><div class="muted">${p.category} · ⭐ 4.4</div><div class="name">${p.name}</div><div class="price">${money(p.price)}</div><div class="muted">${p.stock>0?`${p.stock} in stock`:'Out of stock'}</div><div class="actions"><button class="outline" ${p.stock<1?'disabled':''} onclick="add('${p.id}')">Add</button><button class="pill" onclick="toggleWish('${p.id}')">${state.wishlist.has(p.id)?'❤️':'♡'}</button></div></div></div>`}
function home(){let list=PRODUCTS.filter(p=>(state.cat==='All'||p.category===state.cat)&&p.name.toLowerCase().includes(state.query.toLowerCase()));return `<div class="top"><div class="brand">Shree<b>Kart</b></div><div class="search"><input id="q" value="${state.query}" placeholder="Search products, brands and more" oninput="state.query=this.value;render()"><button class="pill" onclick="go('cart')">🛒 ${state.cart.reduce((a,b)=>a+b.qty,0)}</button></div></div><div class="hero"><div><h1>Shop More, Live Better.</h1><p>Real products. Real orders. One ShreeKart.</p><div class="muted" style="margin-top:8px">🟢 Live catalog connected</div><br><button class="pill" onclick="document.querySelector('.section').scrollIntoView({behavior:'smooth'})">Shop Now</button></div><div style="font-size:80px">🛍️</div></div><div class="section"><h2>Categories</h2><div class="cats">${cats.map(c=>`<button class="cat" onclick="state.cat='${c[1]}';render()"><span>${c[0]}</span>${c[1]}</button>`).join('')}</div></div><div class="section"><div class="row"><h2>${state.cat==='All'?'Products':state.cat}</h2><span class="muted">${list.length} items</span></div><div class="grid">${list.map(productCard).join('')||'<div class="box empty">No products found.</div>'}</div></div>`}
function cart(){if(!state.cart.length)return `<div class="page"><div class="box empty"><div style="font-size:55px">🛒</div><h2>Your cart is empty</h2><button class="pill" onclick="go('home')">Continue Shopping</button></div></div>`;let rows=state.cart.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id);if(!p)return '';return `<div class="box row"><div><b>${p.emoji} ${p.name}</b><div class="muted">${money(p.price)} each · ${p.stock} left</div></div><div class="qty"><button onclick="dec('${p.id}')">−</button><b>${i.qty}</b><button onclick="add('${p.id}')">+</button></div><b>${money(p.price*i.qty)}</b></div>`}).join('');let total=cartTotal();return `<div class="page"><h2>Cart</h2>${rows}<div class="box"><div class="row"><span>Subtotal</span><b>${money(total)}</b></div><div class="row"><span>Delivery</span><span>Free</span></div><hr><div class="row"><h3>Total</h3><h3>${money(total)}</h3></div><button class="pill" style="width:100%" onclick="go('checkout')">Proceed to Checkout</button></div></div>`}
function cartTotal(){return state.cart.reduce((s,i)=>{const p=PRODUCTS.find(p=>p.id===i.id);return s+(p?Number(p.price)*i.qty:0)},0)}
function checkout(){let total=cartTotal();return `<div class="page"><h2>Secure Checkout</h2>${!user?`<div class="box"><b>Login required</b><p class="muted">Sign in before placing a real order.</p><button class="pill" onclick="authBox()">Login / Sign up</button></div>`:''}<div class="box"><h3>📍 Delivery Address</h3>${state.addresses.length?`<select id="savedAddr" style="width:100%;padding:12px;border-radius:10px"><option value="">Use new address</option>${state.addresses.map(a=>`<option value="${a.id}">${a.label||'Address'}: ${a.full_address||''}</option>`).join('')}</select>`:''}<textarea id="addr" style="width:100%;min-height:90px;padding:12px;border:1px solid var(--line);border-radius:10px;margin-top:10px" placeholder="House, street, city, PIN code"></textarea></div><div class="box"><h3>Payment</h3><label><input type="radio" name="pay" value="cod" checked> Cash on Delivery</label><br><label><input type="radio" name="pay" value="online"> Online Payment <small class="muted">(gateway pending)</small></label></div><div class="box"><div class="row"><b>Payable</b><b>${money(total)}</b></div><button class="pill" style="width:100%;margin-top:12px" onclick="placeOrder()">Place Order</button></div></div>`}
async function placeOrder(){
 if(!user){authBox();return}
 let addr=document.querySelector('#addr')?.value?.trim();const saved=document.querySelector('#savedAddr')?.value;
 if(!addr&&saved){const a=state.addresses.find(x=>x.id===saved);addr=a?.full_address||''}
 if(!addr)return toast('Please enter your address');
 const payment=document.querySelector('input[name="pay"]:checked')?.value||'cod';
 if(payment==='online') return toast('Online payment gateway is not live yet. Choose COD for the test order.');
 const items=state.cart.map(i=>({product_id:i.id,quantity:i.qty}));
 if(!items.length)return toast('Cart is empty');
 const {data:orderId,error}=await sb.rpc('place_order',{p_items:items,p_delivery_address:{text:addr},p_payment_method:payment});
 if(error){console.error(error);toast(error.message);return}
 if(user && !saved){ const ar=await sb.from('addresses').insert({user_id:user.id,label:'Home',full_address:addr,is_default:state.addresses.length===0}); if(ar.error) console.error('Address save failed',ar.error); }
 state.cart=[];save();await loadProducts();await loadOrders();toast(`Order placed 🎉 #${String(orderId).slice(-8)}`);go('orders')
}
function orders(){return `<div class="page"><h2>My Orders</h2>${!user?`<div class="box"><p>Login to see your orders.</p><button class="pill" onclick="authBox()">Login / Sign up</button></div>`:state.orders.length?state.orders.map(o=>`<div class="box"><div class="row"><b>Order #${String(o.id).slice(-8)}</b><b>${money(o.total)}</b></div><p class="muted">${new Date(o.created_at).toLocaleString('en-IN')}</p><p>📦 <b>${o.status}</b> · 💳 ${o.payment_status}</p></div>`).join(''):`<div class="box empty">No orders yet.</div>`}</div>`}
function profilePage(){return `<div class="page"><h2>Profile</h2><div class="box">${user?`<div style="font-size:50px">👤</div><h3>${user.email}</h3><button class="outline" onclick="signOut()">Sign out</button>`:`<h3>Welcome to ShreeKart</h3><button class="pill" onclick="authBox()">Login / Sign up</button>`}</div><div class="box"><h3>📍 Saved Addresses</h3>${state.addresses.map(a=>`<p><b>${a.label||'Address'}</b> · ${a.full_address||''}</p>`).join('')||'<p class="muted">No saved addresses</p>'}${user?`<button class="outline" onclick="saveAddress()">+ Add Address</button>`:''}</div><div class="box" onclick="go('wishlist')">❤️ Wishlist</div></div>`}
function wishlist(){let list=PRODUCTS.filter(p=>state.wishlist.has(p.id));return `<div class="page"><h2>❤️ Wishlist</h2><div class="grid">${list.map(productCard).join('')||'<div class="box empty">Your wishlist is empty.</div>'}</div></div>`}
async function saveAddress(){if(!user)return authBox();const text=prompt('Enter complete delivery address');if(!text)return;const label=prompt('Label: Home / Work','Home')||'Home';const {error}=await sb.from('addresses').insert({user_id:user.id,label,full_address:text,is_default:state.addresses.length===0});if(error)toast(error.message);else{await loadAddresses();toast('Address saved 📍');render()}}
function authBox(){if(!sb)return toast('Supabase is not configured');const email=prompt('Enter your email');if(!email)return;const password=prompt('Enter password (minimum 6 characters)');if(!password)return;sb.auth.signInWithPassword({email,password}).then(async({error})=>{if(error){const r=await sb.auth.signUp({email,password});toast(r.error?r.error.message:'Account created. Check your email 📩')}else toast('Welcome back 👋')})}
async function signOut(){await sb.auth.signOut();toast('Signed out');go('home')}
function nav(){return `<div class="bottom"><div class="nav">${[['home','🏠','Home'],['orders','📦','Orders'],['cart','🛒','Cart'],['profile','👤','Profile']].map(n=>`<button class="${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><div style="font-size:20px">${n[1]}</div>${n[2]}</button>`).join('')}</div></div>`}
function go(p){state.page=p;render();scrollTo(0,0)}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function render(){let body=state.page==='home'?home():state.page==='cart'?cart():state.page==='checkout'?checkout():state.page==='orders'?orders():state.page==='wishlist'?wishlist():profilePage();document.querySelector('#app').innerHTML=`<div class="app">${body}</div>${nav()}`}
Object.assign(window,{go,add,dec,toggleWish,placeOrder,authBox,signOut,saveAddress,state});init();
