const sb=window.supabase?.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let PRODUCTS=[],user=null,PROFILE=null;
const cats=[['🛍️','All'],['👕','Fashion'],['📱','Electronics'],['🏠','Home'],['💄','Beauty'],['👟','Footwear'],['📦','Mobiles']];
let state={page:'home',query:'',cat:'All',sort:'newest',maxPrice:'',product:null,cart:JSON.parse(localStorage.getItem('sk_cart')||'[]'),orders:[],wishlist:new Set(),addresses:[],reviews:[]};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const save=()=>localStorage.setItem('sk_cart',JSON.stringify(state.cart));
const emojiFor=c=>({Fashion:'👕',Electronics:'📱',Home:'🏠','Home & Kitchen':'🏠',Beauty:'💄',Mobiles:'📱',Footwear:'👟'})[c]||'🛍️';
async function init(){if(!sb){render();toast('Supabase configuration missing');return}const {data:{user:u}}=await sb.auth.getUser();user=u||null;await refresh();render();sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;await refresh();render()})}
async function refresh(){await loadProfile();await loadProducts();await loadOrders();await loadWishlist();await loadAddresses()}
async function loadProfile(){PROFILE=null;if(!user)return;const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();PROFILE=data}
async function loadProducts(){const {data,error}=await sb.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(error){console.error(error);PRODUCTS=[];toast('Products load failed')}else PRODUCTS=(data||[]).map(p=>({...p,emoji:emojiFor(p.category)}))}
async function loadOrders(){if(!user){state.orders=[];return}let q=sb.from('orders').select('*, order_items(*, products(name,image_url))').order('created_at',{ascending:false});if(!['admin','seller'].includes(PROFILE?.role))q=q.eq('user_id',user.id);const {data,error}=await q;if(error)console.error(error);state.orders=data||[]}
async function loadWishlist(){state.wishlist=new Set();if(!user)return;const {data}=await sb.from('wishlists').select('product_id').eq('user_id',user.id);(data||[]).forEach(x=>state.wishlist.add(x.product_id))}
async function loadAddresses(){state.addresses=[];if(!user)return;const {data}=await sb.from('addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false});state.addresses=data||[]}
async function loadReviews(productId){const {data,error}=await sb.from('reviews').select('id,rating,review_text,created_at,user_id').eq('product_id',productId).order('created_at',{ascending:false});if(error){console.error(error);state.reviews=[]}else state.reviews=data||[]}
function add(id){const p=PRODUCTS.find(x=>x.id===id),x=state.cart.find(i=>i.id===id);if(!p||p.stock<1)return;if(x&&x.qty>=p.stock)return toast('Stock limit reached');x?x.qty++:state.cart.push({id,qty:1});save();toast('Added to cart 🛒');render()}
function dec(id){const x=state.cart.find(i=>i.id===id);if(!x)return;x.qty--;if(x.qty<=0)state.cart=state.cart.filter(i=>i.id!==id);save();render()}
async function toggleWish(id){if(!user)return authBox();if(state.wishlist.has(id)){await sb.from('wishlists').delete().eq('user_id',user.id).eq('product_id',id);state.wishlist.delete(id)}else{const {error}=await sb.from('wishlists').insert({user_id:user.id,product_id:id});if(error)return toast(error.message);state.wishlist.add(id)}render()}
function rating(p){return Number(p.rating_avg||0).toFixed(1)}
function productCard(p){return `<div class="card"><button class="product-click" onclick="openProduct('${p.id}')"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:p.emoji}</div><div class="body"><div class="muted">${esc(p.category)} · ${rating(p)>0?`⭐ ${rating(p)}`:'No ratings'}</div><div class="name">${esc(p.name)}</div><div class="price">${money(p.price)}</div><div class="muted">${p.stock>0?`${p.stock} in stock`:'Out of stock'}</div></div></button><div class="actions"><button class="outline" ${p.stock<1?'disabled':''} onclick="event.stopPropagation();add('${p.id}')">Add</button><button class="pill" onclick="event.stopPropagation();toggleWish('${p.id}')">${state.wishlist.has(p.id)?'❤️':'♡'}</button></div></div>`}
function filtered(){let list=PRODUCTS.filter(p=>(state.cat==='All'||p.category===state.cat)&&p.name.toLowerCase().includes(state.query.toLowerCase()));if(state.maxPrice)list=list.filter(p=>Number(p.price)<=Number(state.maxPrice));if(state.sort==='price_low')list.sort((a,b)=>a.price-b.price);if(state.sort==='price_high')list.sort((a,b)=>b.price-a.price);if(state.sort==='rating')list.sort((a,b)=>Number(b.rating_avg||0)-Number(a.rating_avg||0));return list}
function home(){let list=filtered();return `<div class="top"><div class="brand">Shree<b>Kart</b></div><div class="search"><input value="${esc(state.query)}" placeholder="Search products, brands and more" oninput="state.query=this.value;render()"><button class="pill" onclick="go('cart')">🛒 ${state.cart.reduce((a,b)=>a+b.qty,0)}</button></div></div><div class="hero"><div><h1>Shop More, Live Better.</h1><p>Real products. Real orders. One ShreeKart.</p><div class="muted hero-live">🟢 Live catalog connected</div><button class="pill" onclick="document.querySelector('.section').scrollIntoView({behavior:'smooth'})">Shop Now</button></div><div class="hero-icon">🛍️</div></div><div class="section"><h2>Categories</h2><div class="cats">${cats.map(c=>`<button class="cat ${state.cat===c[1]?'selected':''}" onclick="state.cat='${c[1]}';render()"><span>${c[0]}</span>${c[1]}</button>`).join('')}</div></div><div class="section"><div class="row"><h2>${state.cat==='All'?'Products':esc(state.cat)}</h2><span class="muted">${list.length} items</span></div><div class="filters"><select onchange="state.sort=this.value;render()"><option value="newest" ${state.sort==='newest'?'selected':''}>Newest</option><option value="price_low" ${state.sort==='price_low'?'selected':''}>Price: Low to High</option><option value="price_high" ${state.sort==='price_high'?'selected':''}>Price: High to Low</option><option value="rating" ${state.sort==='rating'?'selected':''}>Top Rated</option></select><input type="number" min="0" placeholder="Max ₹" value="${esc(state.maxPrice)}" onchange="state.maxPrice=this.value;render()"></div><div class="grid">${list.map(productCard).join('')||'<div class="box empty">No products found.</div>'}</div></div>`}
function cart(){if(!state.cart.length)return `<div class="page"><div class="box empty"><div class="big-icon">🛒</div><h2>Your cart is empty</h2><button class="pill" onclick="go('home')">Continue Shopping</button></div></div>`;let rows=state.cart.map(i=>{let p=PRODUCTS.find(x=>x.id===i.id);if(!p)return '';return `<div class="box row"><div><b>${p.emoji} ${esc(p.name)}</b><div class="muted">${money(p.price)} each · ${p.stock} left</div></div><div class="qty"><button onclick="dec('${p.id}')">−</button><b>${i.qty}</b><button onclick="add('${p.id}')">+</button></div><b>${money(p.price*i.qty)}</b></div>`}).join('');let total=cartTotal();return `<div class="page"><h2>Cart</h2>${rows}<div class="box"><div class="row"><span>Subtotal</span><b>${money(total)}</b></div><div class="row"><span>Delivery</span><span>Free</span></div><hr><div class="row"><h3>Total</h3><h3>${money(total)}</h3></div><button class="pill full" onclick="go('checkout')">Proceed to Checkout</button></div></div>`}
function cartTotal(){return state.cart.reduce((s,i)=>{const p=PRODUCTS.find(p=>p.id===i.id);return s+(p?Number(p.price)*i.qty:0)},0)}
function checkout(){let total=cartTotal();return `<div class="page"><h2>Secure Checkout</h2>${!user?`<div class="box"><b>Login required</b><p class="muted">Sign in before placing a real order.</p><button class="pill" onclick="authBox()">Login / Sign up</button><button class="outline small" onclick="resetPassword()">Forgot password</button></div>`:''}<div class="box"><h3>📍 Delivery Address</h3>${state.addresses.length?`<select id="savedAddr" class="field" onchange="document.querySelector('#addr').value=this.value?state.addresses.find(a=>a.id===this.value)?.full_address||'':''"><option value="">Use new address</option>${state.addresses.map(a=>`<option value="${a.id}">${esc(a.label||'Address')}: ${esc(a.full_address||'')}</option>`).join('')}</select>`:''}<textarea id="addr" class="field" placeholder="House, street, city, PIN code"></textarea></div><div class="box"><h3>Payment</h3><label><input type="radio" name="pay" value="cod" checked> Cash on Delivery</label><br><label><input type="radio" name="pay" value="online"> Online Payment <small class="muted">(gateway integration required)</small></label></div><div class="box"><div class="row"><b>Payable</b><b>${money(total)}</b></div><button class="pill full mt" onclick="placeOrder()">Place Order</button></div></div>`}
async function placeOrder(){if(!user)return authBox();let addr=document.querySelector('#addr')?.value?.trim(),saved=document.querySelector('#savedAddr')?.value;if(!addr&&saved)addr=state.addresses.find(x=>x.id===saved)?.full_address||'';if(!addr)return toast('Please enter your address');const payment=document.querySelector('input[name="pay"]:checked')?.value||'cod';if(payment==='online')return toast('Online payment needs a verified payment gateway first.');const items=state.cart.map(i=>({product_id:i.id,quantity:i.qty}));if(!items.length)return toast('Cart is empty');const {data:orderId,error}=await sb.rpc('place_order',{p_items:items,p_address:{text:addr},p_payment_method:payment});if(error)return toast(error.message);if(!saved){await sb.from('addresses').insert({user_id:user.id,label:'Home',full_address:addr,is_default:state.addresses.length===0})}state.cart=[];save();await refresh();toast(`Order placed 🎉 #${String(orderId).slice(-8)}`);go('orders')}
function statusSteps(status){const steps=['placed','confirmed','packed','shipped','delivered'];if(status==='cancelled')return `<div class="cancelled">❌ Cancelled</div>`;let idx=steps.indexOf(status);return `<div class="timeline">${steps.map((s,i)=>`<div class="step ${i<=idx?'done':''}"><span>${i<=idx?'✓':'○'}</span><small>${s}</small></div>`).join('')}</div>`}
function orders(){return `<div class="page"><h2>My Orders</h2>${!user?`<div class="box"><p>Login to see your orders.</p><button class="pill" onclick="authBox()">Login / Sign up</button><button class="outline small" onclick="resetPassword()">Forgot password</button></div>`:state.orders.length?state.orders.map(o=>`<div class="box"><div class="row"><b>Order #${String(o.id).slice(-8)}</b><b>${money(o.total)}</b></div><p class="muted">${new Date(o.created_at).toLocaleString('en-IN')}</p>${statusSteps(o.status)}<p>💳 ${esc(o.payment_status)} · ${esc(o.payment_method)}</p><div class="order-items">${(o.order_items||[]).map(i=>`<span>${esc(i.products?.name||'Product')} × ${i.quantity}</span>`).join('')}</div></div>`).join(''):`<div class="box empty">No orders yet.</div>`}</div>`}
function profilePage(){let admin=PROFILE?.role==='admin'||PROFILE?.role==='seller';return `<div class="page"><h2>Profile</h2><div class="box">${user?`<div class="big-icon">👤</div><h3>${esc(user.email)}</h3><p class="muted">Role: ${esc(PROFILE?.role||'customer')}</p><button class="outline" onclick="signOut()">Sign out</button>`:`<h3>Welcome to ShreeKart</h3><button class="pill" onclick="authBox()">Login / Sign up</button><button class="outline small" onclick="resetPassword()">Forgot password</button>`}</div><div class="box"><h3>📍 Saved Addresses</h3>${state.addresses.map(a=>`<div class="address"><b>${esc(a.label||'Address')}</b>${a.is_default?'<span class="tag">Default</span>':''}<p>${esc(a.full_address||'')}</p><button class="outline small" onclick="editAddress('${a.id}')">Edit</button> <button class="outline small danger" onclick="deleteAddress('${a.id}')">Delete</button></div>`).join('')||'<p class="muted">No saved addresses</p>'}${user?`<button class="outline" onclick="saveAddress()">+ Add Address</button>`:''}</div><div class="box clickable" onclick="go('wishlist')">❤️ Wishlist</div>${admin?`<div class="box clickable" onclick="go('admin')">🛠️ ${PROFILE.role==='admin'?'Admin':'Seller'} Dashboard</div>`:''}</div>`}
function wishlist(){let list=PRODUCTS.filter(p=>state.wishlist.has(p.id));return `<div class="page"><h2>❤️ Wishlist</h2><div class="grid">${list.map(productCard).join('')||'<div class="box empty">Your wishlist is empty.</div>'}</div></div>`}
async function saveAddress(id){if(!user)return authBox();let existing=id?state.addresses.find(a=>a.id===id):null;let text=prompt('Complete delivery address',existing?.full_address||'');if(!text)return;let label=prompt('Label: Home / Work',existing?.label||'Home')||'Home';let payload={user_id:user.id,label,full_address:text,is_default:existing?.is_default??state.addresses.length===0};let res=id?await sb.from('addresses').update(payload).eq('id',id).eq('user_id',user.id):await sb.from('addresses').insert(payload);if(res.error)toast(res.error.message);else{await loadAddresses();toast('Address saved 📍');render()}}
const editAddress=id=>saveAddress(id);
async function deleteAddress(id){if(!user||!confirm('Delete this address?'))return;const {error}=await sb.from('addresses').delete().eq('id',id).eq('user_id',user.id);if(error)return toast(error.message);await loadAddresses();render()}
async function openProduct(id){state.product=PRODUCTS.find(p=>p.id===id);if(!state.product)return;await loadReviews(id);state.page='product';render();scrollTo(0,0)}
function productPage(){let p=state.product;if(!p)return home();let avg=rating(p),reviews=state.reviews;return `<div class="page"><button class="outline" onclick="go('home')">← Back</button><div class="product-detail"><div class="detail-pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:p.emoji}</div><div><div class="muted">${esc(p.category)} · ${avg>0?'⭐ '+avg:'No ratings yet'}</div><h1>${esc(p.name)}</h1><div class="detail-price">${money(p.price)}</div><p>${esc(p.description||'No description available.')}</p><p class="muted">${p.stock>0?`${p.stock} available`:'Out of stock'}</p><button class="pill" ${p.stock<1?'disabled':''} onclick="add('${p.id}')">Add to Cart</button><button class="outline" onclick="toggleWish('${p.id}')">${state.wishlist.has(p.id)?'❤️ Saved':'♡ Wishlist'}</button></div></div><div class="box"><h3>⭐ Reviews</h3>${user?`<button class="outline" onclick="writeReview('${p.id}')">Write a review</button>`:''}${reviews.map(r=>`<div class="review"><b>⭐ ${r.rating}/5</b><p>${esc(r.review_text||'')}</p><small class="muted">Customer · ${new Date(r.created_at).toLocaleDateString('en-IN')}</small></div>`).join('')||'<p class="muted">No reviews yet.</p>'}</div></div>`}
async function writeReview(id){if(!user)return authBox();let rating=Number(prompt('Rating 1-5','5'));if(!rating||rating<1||rating>5)return toast('Rating must be 1 to 5');let text=prompt('Review');const {error}=await sb.from('reviews').upsert({user_id:user.id,product_id:id,rating,review_text:text||''},{onConflict:'user_id,product_id'});if(error)return toast(error.message);toast('Review saved ⭐');await loadProducts();await loadReviews(id);render()}
function admin(){if(!['admin','seller'].includes(PROFILE?.role))return `<div class="page"><div class="box empty">Admin access required.</div></div>`;return `<div class="page"><h2>🛠️ ${PROFILE.role==='admin'?'Admin':'Seller'} Dashboard</h2><div class="admin-grid"><div class="stat"><b>${PRODUCTS.length}</b><small>Active products</small></div><div class="stat"><b>${state.orders.length}</b><small>Orders</small></div><div class="stat"><b>${PRODUCTS.reduce((s,p)=>s+p.stock,0)}</b><small>Units in catalog</small></div></div><div class="box"><h3>Add Product</h3><input id="pn" class="field full" placeholder="Product name"><input id="pc" class="field full mt" placeholder="Category"><input id="pp" class="field full mt" type="number" placeholder="Price"><input id="ps" class="field full mt" type="number" placeholder="Stock"><input id="pi" class="field full mt" placeholder="Image URL (optional)"><textarea id="pd" class="field full mt" placeholder="Description"></textarea><button class="pill full mt" onclick="addProduct()">Add Product</button></div><div class="box"><h3>Catalog</h3>${PRODUCTS.map(p=>`<div class="row admin-product"><span><b>${esc(p.name)}</b><small class="muted">${money(p.price)} · ${p.stock} stock</small></span><button class="outline small danger" onclick="deactivateProduct('${p.id}')">Deactivate</button></div>`).join('')}</div>${state.orders.map(o=>`<div class="box"><div class="row"><b>#${String(o.id).slice(-8)}</b><select onchange="updateOrder('${o.id}',this.value)">${['placed','confirmed','packed','shipped','delivered','cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></div><p>${money(o.total)} · ${esc(o.payment_method)}</p></div>`).join('')}</div>`}
async function addProduct(){if(!['admin','seller'].includes(PROFILE?.role))return;let name=document.querySelector('#pn')?.value.trim(),category=document.querySelector('#pc')?.value.trim(),price=Number(document.querySelector('#pp')?.value),stock=Number(document.querySelector('#ps')?.value),image_url=document.querySelector('#pi')?.value.trim(),description=document.querySelector('#pd')?.value.trim();if(!name||!category||!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0)return toast('Enter valid product details');const {error}=await sb.from('products').insert({seller_id:user.id,name,category,price,stock,image_url:image_url||null,description:description||null});if(error)return toast(error.message);toast('Product added 🛍️');await loadProducts();render()}
async function deactivateProduct(id){if(!['admin','seller'].includes(PROFILE?.role))return;const {error}=await sb.from('products').update({active:false}).eq('id',id);if(error)return toast(error.message);toast('Product deactivated');await loadProducts();render()}
async function updateOrder(id,status){if(!['admin','seller'].includes(PROFILE?.role))return;const {error}=await sb.from('orders').update({status}).eq('id',id);if(error)toast(error.message);else{toast('Order status updated');await loadOrders();render()}}
async function authBox(){if(!sb)return toast('Supabase is not configured');let email=prompt('Email');if(!email)return;email=email.trim().toLowerCase();let password=prompt('Password (minimum 6 characters)');if(!password)return;if(password.length<6)return toast('Password must be at least 6 characters');const {error}=await sb.auth.signInWithPassword({email,password});if(!error)return toast('Welcome back 👋');const r=await sb.auth.signUp({email,password,options:{data:{full_name:email.split('@')[0]}}});if(r.error)return toast(r.error.message);toast('Account created. Check your email 📩')}
async function resetPassword(){if(!sb)return toast('Supabase is not configured');let email=prompt('Enter your account email');if(!email)return;const {error}=await sb.auth.resetPasswordForEmail(email.trim().toLowerCase());toast(error?error.message:'Password reset email sent 📩')}
async function signOut(){await sb.auth.signOut();toast('Signed out');go('home')}
function nav(){return `<div class="bottom"><div class="nav">${[['home','🏠','Home'],['orders','📦','Orders'],['cart','🛒','Cart'],['profile','👤','Profile']].map(n=>`<button class="${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><div>${n[1]}</div>${n[2]}</button>`).join('')}</div></div>`}
function go(p){state.page=p;render();scrollTo(0,0)}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2400)}
function render(){let body=state.page==='home'?home():state.page==='cart'?cart():state.page==='checkout'?checkout():state.page==='orders'?orders():state.page==='wishlist'?wishlist():state.page==='product'?productPage():state.page==='admin'?admin():profilePage();document.querySelector('#app').innerHTML=`<div class="app">${body}</div>${nav()}`}
Object.assign(window,{go,add,dec,toggleWish,placeOrder,authBox,resetPassword,signOut,saveAddress,editAddress,deleteAddress,openProduct,writeReview,updateOrder,addProduct,deactivateProduct,state});init();
