"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
type Product={id:string;name:string;category?:string;price:number;stock:number;image_url?:string|null;rating_avg?:number|null};
type Order={id:string;status:string;payment_method:string;payment_status:string;total:number;shipping_address:any;created_at:string};
type Address={id:string;label:string;full_address:string;city?:string;state?:string;pincode?:string;is_default?:boolean};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const sb=url&&key?createClient(url,key):null;
export default function Home(){
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(""),[cat,setCat]=useState("All"),[cart,setCart]=useState<Record<string,number>>({});
 const [view,setView]=useState<"shop"|"cart"|"account"|"orders"|"addresses"|"wishlist">("shop"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[msg,setMsg]=useState("");
 const [user,setUser]=useState<any>(null),[busy,setBusy]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [orders,setOrders]=useState<Order[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[wishlist,setWishlist]=useState<string[]>([]);
 const [address,setAddress]=useState({label:"Home",full_address:"",city:"",state:"",pincode:""});
 useEffect(()=>{if(!sb){setError("Supabase environment variables are missing.");setLoading(false);return}
   sb.auth.getUser().then(async({data})=>{setUser(data.user);if(data.user)loadPrivate(data.user.id)});
   sb.from("products").select("*").eq("active",true).order("created_at",{ascending:false}).then(({data,error})=>{if(error)setError(error.message);else setProducts(data||[]);setLoading(false)});
 },[]);
 async function loadPrivate(uid:string){if(!sb)return;const [o,a,w]=await Promise.all([sb.from("orders").select("*").eq("user_id",uid).order("created_at",{ascending:false}),sb.from("addresses").select("*").eq("user_id",uid).order("is_default",{ascending:false}),sb.from("wishlists").select("product_id").eq("user_id",uid)]);if(!o.error)setOrders(o.data||[]);if(!a.error)setAddresses(a.data||[]);if(!w.error)setWishlist((w.data||[]).map((x:any)=>x.product_id));}
 const cats=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category).filter(Boolean) as string[]))],[products]);
 const list=products.filter(p=>(cat==="All"||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase()));
 const items=Object.entries(cart).map(([id,qty])=>({p:products.find(p=>p.id===id)!,qty})).filter(x=>x.p);
 const total=items.reduce((s,x)=>s+x.p.price*x.qty,0),count=Object.values(cart).reduce((a,b)=>a+b,0);
 function add(p:Product){setCart(c=>({...c,[p.id]:Math.min((c[p.id]||0)+1,p.stock)}));setMsg(p.name+" added to cart.");}
 function change(id:string,n:number){setCart(c=>{const x={...c};if(n<=0)delete x[id];else x[id]=n;return x})}
 async function auth(mode:"login"|"signup"){if(!sb)return;setBusy(true);setMsg("");const r=mode==="login"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});setBusy(false);if(r.error)setMsg(r.error.message);else{setUser(r.data.user);if(r.data.user)await loadPrivate(r.data.user.id);setMsg(mode==="signup"?"Account created. Check your email if confirmation is enabled.":"Signed in.");}}
 async function checkout(){if(!sb||!user){setView("account");setMsg("Please sign in before checkout.");return}if(!addresses.length){setView("addresses");setMsg("Add a delivery address first.");return}setBusy(true);const selected=addresses.find(a=>a.is_default)||addresses[0];const rows=items.map(x=>({product_id:x.p.id,quantity:x.qty}));const {error}=await sb.rpc("place_order",{p_items:rows,p_address:selected,p_payment_method:"cod"});setBusy(false);if(error)setMsg(error.message);else{setCart({});await loadPrivate(user.id);setView("orders");setMsg("Order placed successfully.");}}
 async function saveAddress(){if(!sb||!user||!address.full_address){setMsg("Full address is required.");return}setBusy(true);const r=await sb.from("addresses").insert({...address,user_id:user.id,is_default:addresses.length===0});setBusy(false);if(r.error)setMsg(r.error.message);else{setAddress({label:"Home",full_address:"",city:"",state:"",pincode:""});await loadPrivate(user.id);setMsg("Address saved.");}}
 async function toggleWish(id:string){if(!sb||!user){setView("account");setMsg("Please sign in to use wishlist.");return}if(wishlist.includes(id)){await sb.from("wishlists").delete().eq("user_id",user.id).eq("product_id",id);setWishlist(x=>x.filter(v=>v!==id));}else{const r=await sb.from("wishlists").insert({user_id:user.id,product_id:id});if(!r.error)setWishlist(x=>[...x,id]);}}
 function privateGate(next:any){if(!user){setView("account");setMsg("Please sign in first.");return}setView(next);setMsg("");}
 return <main>
 <header><div className="brand" onClick={()=>setView("shop")}>Shree<span>Kart</span></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, brands and more"/><button className="navbtn" onClick={()=>privateGate("orders")}>📦 Orders</button><button className="navbtn" onClick={()=>privateGate("wishlist")}>♡ {wishlist.length}</button><button className="navbtn" onClick={()=>setView("account")}>👤 {user?"Account":"Login"}</button><button className="navbtn" onClick={()=>setView("cart")}>🛒 {count}</button></header>
 {view==="shop"&&<><section className="hero"><div><p className="eyebrow">SHREEKART</p><h1>Shop More, Live Better.</h1><p>Fresh catalog, secure accounts, orders and COD checkout.</p></div><div className="heroIcon">🛍️</div></section><section className="cats">{cats.map(c=><button className={cat===c?"selected":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</section>{msg&&<div className="toast">{msg}</div>}{loading?<div className="state">Loading products…</div>:error?<div className="state error">{error}</div>:<section className="grid">{list.map(p=><article className="card" key={p.id}><div className="photo">{p.image_url?<img src={p.image_url} alt={p.name}/>:<span>🛍️</span>}<button className="heart" onClick={()=>toggleWish(p.id)}>{wishlist.includes(p.id)?"♥":"♡"}</button></div><div className="body"><small>{p.category||"Product"} {p.rating_avg?"· ⭐ "+Number(p.rating_avg).toFixed(1):""}</small><h3>{p.name}</h3><strong>₹{Number(p.price).toLocaleString("en-IN")}</strong><p>{p.stock>0?p.stock+" in stock":"Out of stock"}</p><button disabled={!p.stock} onClick={()=>add(p)}>Add to Cart</button></div></article>)}</section>}</>}
 {view==="cart"&&<section className="panel"><h2>Your Cart</h2>{!items.length?<p>Your cart is empty.</p>:<>{items.map(x=><div className="row" key={x.p.id}><b>{x.p.name}</b><span>₹{x.p.price.toLocaleString("en-IN")}</span><div><button onClick={()=>change(x.p.id,x.qty-1)}>−</button> {x.qty} <button onClick={()=>change(x.p.id,Math.min(x.qty+1,x.p.stock))}>+</button></div></div>)}<h2>Total: ₹{total.toLocaleString("en-IN")}</h2><button className="primary" disabled={busy} onClick={checkout}>{busy?"Placing order…":"Place COD Order"}</button></>}</section>}
 {view==="orders"&&<section className="panel"><h2>My Orders</h2>{!orders.length?<p>No orders yet.</p>:orders.map(o=><div className="order" key={o.id}><div><b>Order #{o.id.slice(0,8)}</b><span>{new Date(o.created_at).toLocaleDateString("en-IN")}</span></div><strong>₹{Number(o.total).toLocaleString("en-IN")}</strong><p>Status: <b>{o.status}</b> · Payment: {o.payment_method.toUpperCase()}</p></div>)}</section>}
 {view==="addresses"&&<section className="panel"><h2>Delivery Addresses</h2>{addresses.map(a=><div className="order" key={a.id}><b>{a.label} {a.is_default?"· Default":""}</b><p>{a.full_address}, {a.city}, {a.state} - {a.pincode}</p></div>)}<h3>Add address</h3><input className="field" placeholder="Label e.g. Home" value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/><input className="field" placeholder="Full address" value={address.full_address} onChange={e=>setAddress({...address,full_address:e.target.value})}/><div className="two"><input className="field" placeholder="City" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><input className="field" placeholder="State" value={address.state} onChange={e=>setAddress({...address,state:e.target.value})}/></div><input className="field" placeholder="PIN code" value={address.pincode} onChange={e=>setAddress({...address,pincode:e.target.value})}/><button className="primary" disabled={busy} onClick={saveAddress}>Save Address</button></section>}
 {view==="wishlist"&&<section className="panel"><h2>Wishlist</h2>{!wishlist.length?<p>No saved products yet.</p>:<div className="wishlist">{wishlist.map(id=>{const p=products.find(x=>x.id===id);return p?<div className="wish" key={id}><b>{p.name}</b><span>₹{Number(p.price).toLocaleString("en-IN")}</span><button onClick={()=>add(p)}>Add to Cart</button><button onClick={()=>toggleWish(id)}>Remove</button></div>:null})}</div>}</section>}
 {view==="account"&&<section className="panel">{user?<><h2>Account</h2><p>Signed in as <b>{user.email}</b></p><div className="actions"><button onClick={()=>setView("orders")}>📦 My Orders</button><button onClick={()=>setView("addresses")}>📍 Addresses</button><button onClick={()=>setView("wishlist")}>♡ Wishlist</button></div><button className="primary" onClick={async()=>{await sb?.auth.signOut();setUser(null);setOrders([]);setAddresses([]);setWishlist([]);setView("shop");setMsg("Signed out.");}}>Sign out</button></>:<><h2>Login / Create Account</h2><input className="field" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="field" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="actions"><button className="primary" disabled={busy} onClick={()=>auth("login")}>Login</button><button onClick={()=>auth("signup")}>Create account</button></div></>}{msg&&<p className="notice">{msg}</p>}</section>}
 <footer><b>Cart total: ₹{total.toLocaleString("en-IN")}</b><span>ShreeKart · Supabase powered</span></footer>
 </main>
}